;; -*- no-byte-compile: t; -*-
(package! aggressive-indent)
;; (package! docker-compose-mode)
;; (package! doom-themes :recipe (:host github :repo "loganlinn/doom-themes"))
(package! evil-cleverparens :recipe (:host github :repo "emacs-evil/evil-cleverparens") :pin "134fe3396f975fb1ad261f52cd113f42ac1da4fc")
(package! fnm :recipe (:host github :repo "bobrowadam/fnm.el"))
;; (package! git-auto-commit-mode :recipe (:host github :repo "ryuslash/git-auto-commit-mode"))
;; (package! git-spice :recipe (:host github :repo "/jesse-c/git-spice.el" :files ("*.el")))
;; (package! kagi)
;; (package! keycast)
(package! mermaid-mode)
(package! mise)
;; (package! outshine) ;; org-mode for non-org buffers
;; (package! prisma-mode :recipe (:host github :repo "pimeys/emacs-prisma-mode" :branch "main"))
;; (package! codeium :disable t :recipe (:host github :repo "Exafunction/codeium.el"))
;; (package! copilot-chat :disable t)
;; (package! evil-visual-mark-mode :recipe (:host github :repo "roman/evil-visual-mark-mode"))
;; (package! fence-edit :recipe (:host github :repo "aaronbieber/fence-edit.el") :pin "fab7cee16e91c2d8f9c24e2b08e934fa0813a774")
;; (package! gh-notify :disable t)
;; (package! graphviz-dot-mode :disable t)
;; (package! highlight-parentheses)
(package! kkp)
;; (package! kubel :disable t)
;; (package! kubel-evil :disable t)
;; (package! minions :disable t)
;; (package! ob-mermaid :disable t)
;; (package! obsidian :disable t)
;; (package! ox-gist :recipe (:host github :repo "punchagan/ox-gist") :pin "e9f1f11af0e97fee30c2b15b56c236b1f4e1f400")
;; (package! parseclj)
;; (package! parseedn)
;; (package! passage :recipe (:host github :repo "anticomputer/passage" :pin "e7385ecbb6aa857a799424d7838bd93624fa2d9c"))
;; (package! protobuf-mode :recipe (:host github :repo "protocolbuffers/protobuf" :files ("editors/protobuf-mode.el")) :pin "28e573e77fc3b453dd242e3848b19e7adbf04984" :disable t)
;; (package! v-mode :disable t)
;; (package! vala-mode :disable t)
;; (package! vertico-posframe :recipe (:host github :repo "tumashu/vertico-posframe") :pin "db9fbc95bb8316165ec74e500a76d6857e6ced1a" :disable t)
;; (package! yuck-mode :disable t)
;; (package! zprint-mode :disable t)
